# Generated by Django 5.0.3 on 2024-05-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_registration_otp_created_at'),
        ('product', '0003_alter_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.vendor'),
        ),
    ]
