# Generated by Django 5.0.3 on 2024-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_registration_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.IntegerField(default=1, max_length=11),
        ),
    ]
