# Generated by Django 5.0.3 on 2024-05-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_registration_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='vendor_id',
            field=models.BooleanField(default=False),
        ),
    ]
