# Generated by Django 5.0.3 on 2024-05-02 14:39

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', shortuuid.django_fields.ShortUUIDField(alphabet='abdc30', length=10, max_length=30, prefix='ven', unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='vendos')),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('shipping_rating', models.CharField(max_length=500)),
                ('days_returns', models.CharField(max_length=500)),
                ('warenty_period', models.CharField(max_length=500)),
                ('authentic_rating', models.CharField(max_length=500)),
                ('chat_res', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
