# Generated by Django 5.0.3 on 2024-05-02 19:19

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_vendor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', shortuuid.django_fields.ShortUUIDField(alphabet='abdc30', length=10, max_length=30, prefix='cat', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
