# Generated by Django 5.0.3 on 2024-05-02 21:40

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_delete_vendor'),
        ('vendor', '0002_alter_vendor_image_alter_vendor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', shortuuid.django_fields.ShortUUIDField(alphabet='abdc30', length=20, max_length=30, prefix='pro', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_image')),
                ('description', models.TextField()),
                ('product_details', models.TextField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=60)),
                ('specification', models.TextField(verbose_name='')),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('in review', 'In Review'), ('approved', 'Approved')], default='in review', max_length=50)),
                ('in_stock', models.BooleanField(default=False)),
                ('features', models.BooleanField(default=False)),
                ('digital', models.BooleanField(default=False)),
                ('my_stock', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
